### ISSUE TITLE
Detect all elements that you have in your bower folder ?

### ISSUE THREAD

**Issue by joeblew99** [peterblazejewicz/vscode-polymer-snippets#1]
Thanks for writing this. Its the only vscode tool relating to Polymer out there from what i could see.

It would be super cool, if there was a way to detect the components you have in your bower, as a basic for what the tool prompts ? I can already see that the answer is no because its just currently designed to work off the hard coded snippets file.

**Comment by peterblazejewicz** [comment]
This is kind of neglected project. Have you seen this Twitter thread?
https://twitter.com/rob_dodson/status/757387892796723200
Maybe there will be fully fledged, community driven tool for VSCode and Polymer?
Thanks!

**Comment by peterblazejewicz** [comment]
This should be used for autocompletion in VSCode:
https://github.com/Polymer/polymer-editor-service
This project (older fork) was just a way to provide some common project templates to start with Polymer 1.*
