### ISSUE TITLE
Doesn't work with Polymer Syntax extension

### ISSUE THREAD

**Issue by pdesjardins90** [peterblazejewicz/vscode-polymer-snippets#2]
Because of this setting with 'Polymer Syntax' extension for vs code: 
````json
"files.associations": {
    "*.html": "polymer"
}
````

snippets do not autocomplete in html files, any way to fix this/ work around?

**Comment by peterblazejewicz** [comment]
hi,
maybe this would work (not tested):
```json
{
    "contributes": {
        "snippets": [{
            "language": "html",
            "path": "./snippets/snippets.json"
        }, {
            "language": "polymer",
            "path": "./snippets/snippets.json"
        }]
    }
}
```
AFAIK `polymer-language` sets the language support, so snippets should just advertise support for `polymer`?
https://github.com/jonathanwolfe/language-polymer
So you should just edit language support definition in extension installation (sorry for the problem, but I haven't touched this for a year or so)

**Comment by pdesjardins90** [comment]
wrong repo actually, my bad

**Comment by peterblazejewicz** [comment]
NP
